#!/usr/bin/env php
<?php

$vendorDir = realpath(__DIR__.'/../../../vendor');
echo $vendorDir;
require_once $vendorDir.'/symfony-cmf/testing/bootstrap/bootstrap.php';
require_once __DIR__.'/AppKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;

$kernel = new AppKernel('test', true);
$kernel->setConfigFilename('default.yml');
$application = new Application($kernel);
$application->run();
